# Generated by Django 5.2 on 2025-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('responsible', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('L', 'Baixa'), ('M', 'Média'), ('H', 'Alta')], max_length=1)),
            ],
        ),
    ]
