# Generated by Django 5.2 on 2025-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='tx_title', max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(db_column='tx_description', max_length=500, verbose_name='Descrição')),
                ('responsible', models.CharField(db_column='tx_responsible', max_length=100, verbose_name='Responsável')),
                ('priority', models.CharField(choices=[('L', 'Baixa'), ('M', 'Média'), ('H', 'Alta')], db_column='tx_priority', max_length=1, verbose_name='Prioridade')),
            ],
        ),
    ]
